apiVersion: db.flanksource.com/v1
kind: RedisDB
metadata:
  name: redisdb-basic
  namespace: redis-operator
spec:
  storage:
    storageClass: local-path
  redis:
    replicas: 3
  sentinel:
    replicas: 3
