apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: redis-db
spec:
  source:
    apiVersion: db.flanksource.com/v1
    kind: RedisDB
  resources:
    - apiVersion: databases.spotahome.com/v1
      kind: RedisFailover
      metadata:
        name: "{{.metadata.name}}"
        namespace: "{{.metadata.namespace}}"
      spec:
        sentinel:
          image: 'docker.io/library/redis:{{ .spec.version | default "5.0-alpine" }}'
          replicas: '{{.spec.sentinel.replicas | default "3"}}'
          resources:
            requests:
              cpu: '{{.spec.sentinel.resources.requests.cpu | default "100m"}}'
              memory: '{{.spec.sentinel.resources.requests.memory | default "100Mi"}}'
            limits:
              cpu: '{{.spec.sentinel.resources.limits.cpu | default "100m"}}'
              memory: '{{.spec.sentinel.resources.limits.memory | default "100Mi"}}'
        redis:
          image: 'docker.io/library/redis:{{ .spec.version | default "5.0-alpine" }}'
          replicas: '{{.spec.redis.replicas | default "3"}}'
          resources:
            requests:
              cpu: '{{.spec.redis.resources.requests.cpu | default "100m"}}'
              memory: '{{.spec.redis.resources.requests.memory | default "500Mi"}}'
            limits:
              cpu: '{{.spec.redis.resources.limits.cpu | default "100m"}}'
              memory: '{{.spec.redis.resources.limits.memory | default "500Mi"}}'
          storage:
            persistentVolumeClaim:
              metadata:
                name: "{{.metadata.name}}-persistent-data"
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: '{{.spec.storage.size | default "1Gi"}}'
                storageClassName: '{{.spec.storage.storageClass | default ""}}'
